name: rot13_converter
description: ROT13 (rotate by 13 places) converter using dart:convert library.
version: 0.0.3
homepage: https://github.com/sunaoka/dart-rot13-converter

environment:
  sdk: '>=2.12.0 <4.0.0'

dev_dependencies:
  analyzer: '>=1.7.0'
  test: '>=1.16.0'
  coverage: '>=1.0.3'
