name: Dart

on:
  pull_request:
    branches: [ develop ]
  push:
    branches: [ develop ]
  schedule:
    - cron: '23 1 * * *'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        sdk: [stable, beta, dev]
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: ${{ matrix.sdk }}
      - name: install dependencies
        run: dart pub get
      - name: dart format
        run: dart format --output=none --set-exit-if-changed .
      - name: analyzer
        run: dart analyze --fatal-infos --fatal-warnings .
      - name: run test
        run: dart run test . --coverage=coverage
      - name: coverage
        run: dart run coverage:format_coverage --lcov --packages=.packages --in coverage --out lcov.info
      - uses: codecov/codecov-action@v2
        with:
          files: lcov.info
